DROP TABLE [brainwaves].[DimMODE]
GO
DROP TABLE [brainwaves].[DimSCENARIO]
GO
DROP TABLE [brainwaves].[DimELECTRODE]
GO
DROP TABLE [brainwaves].[DimFREQUENCY]
GO
DROP TABLE [brainwaves].[DimSESSION]
GO
DROP TABLE [brainwaves].[TmpREADING] 
GO
DROP TABLE [brainwaves].[FactREADING] 
GO
CREATE TABLE [brainwaves].[DimMODE] (
  [MODE_ID] 	INT			NOT NULL,
  [MODE]		NVARCHAR (50)	NOT NULL
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
GO
ALTER TABLE [brainwaves].[DimMODE] ADD CONSTRAINT PK_DimMODE_MODE_ID PRIMARY KEY NONCLUSTERED (MODE_ID) NOT ENFORCED
GO
CREATE TABLE [brainwaves].[DimSCENARIO] (
  [SCENARIO_ID]  INT            NOT NULL,
  [SCENARIO]     NVARCHAR (100) NOT NULL
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
GO
ALTER TABLE [brainwaves].[DimSCENARIO] ADD CONSTRAINT PK_DimSCENARIO_SCENARIO_ID PRIMARY KEY NONCLUSTERED (SCENARIO_ID) NOT ENFORCED
GO
CREATE TABLE [brainwaves].[DimELECTRODE] (
  [ELECTRODE_ID] 	INT			NOT NULL,
  [ELECTRODE]	NVARCHAR (50)	NOT NULL,
  [LOCATION]	NVARCHAR (50)	NOT NULL
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
GO
ALTER TABLE [brainwaves].[DimELECTRODE] ADD CONSTRAINT PK_DimELECTRODE_ELECTRODE_ID PRIMARY KEY NONCLUSTERED (ELECTRODE_ID) NOT ENFORCED
GO
CREATE TABLE [brainwaves].[DimFREQUENCY]
(
  [FREQUENCY_ID] 	INT			NOT NULL,
  [FREQUENCY]	NVARCHAR (50) 	NOT NULL,
  [ACTIVITY]	NVARCHAR (100)	NOT NULL
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
GO
ALTER TABLE [brainwaves].[DimFREQUENCY] ADD CONSTRAINT PK_DimMODE_FREQUENCY_ID PRIMARY KEY NONCLUSTERED (FREQUENCY_ID) NOT ENFORCED
GO
CREATE TABLE [brainwaves].[DimSESSION] (
  [SESSION_ID] 	INT           NOT NULL,
  [SCENARIO_ID] 	INT           NOT NULL,
  [MODE_ID] 	INT           NOT NULL,
  [SESSION_DATETIME]	DATETIME      NOT NULL
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
GO
ALTER TABLE [brainwaves].[DimSESSION] ADD CONSTRAINT PK_DimSESSION_SESSION_ID PRIMARY KEY NONCLUSTERED (SESSION_ID) NOT ENFORCED
GO
CREATE TABLE [brainwaves].[TmpREADING] 
(
  [READING_ID]    INT           NOT NULL,
  [SESSION_ID] 	INT           NOT NULL,
  [ELECTRODE_ID] 	INT		  NOT NULL,
  [FREQUENCY_ID] 	INT		  NOT NULL,
  [READING_DATETIME]  DATETIME  NOT NULL,
  [COUNT]      	INT           NOT NULL,
  [VALUE]		DECIMAL(7,3)  NOT NULL
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = ROUND_ROBIN
)
GO
ALTER TABLE [brainwaves].[TmpREADING] ADD CONSTRAINT UNIQUE_TmpREADING_READING_ID_SESSION_ID UNIQUE (READING_ID, SESSION_ID) NOT ENFORCED
GO
CREATE TABLE [brainwaves].[FactREADING] 
(
  [SESSION_DATETIME]   DATETIME 		NOT NULL,
  [READING_DATETIME]   DATETIME  		NOT NULL,
  [SCENARIO]		   NVARCHAR (100)	NOT NULL,
  [ELECTRODE]		   NVARCHAR (50)	NOT NULL,
  [FREQUENCY]		   NVARCHAR (50)  	NOT NULL,
  [VALUE]		   DECIMAL(7,3)  	NOT NULL
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = HASH ([FREQUENCY])
)
