SELECT TOP (10) [MODE_ID], [MODE]
FROM [brainwaves].[DimMODE]

SELECT TOP (10) [ELECTRODE_ID], [ELECTRODE], [LOCATION]
FROM [brainwaves].[DimELECTRODE]

SELECT TOP (10) [FREQUENCY_ID], [FREQUENCY], [ACTIVITY]
FROM [brainwaves].[DimFREQUENCY]

SELECT TOP (10) [SCENARIO_ID], [SCENARIO]
FROM [brainwaves].[DimSCENARIO]

SELECT TOP (10) [SESSION_ID], [SCENARIO_ID], [MODE_ID], [SESSION_DATETIME]
FROM [brainwaves].[DimSESSION]
