--CREATE SCHEMA dimensional

CREATE TABLE [dimensional].[MODE] (
    [MODE_ID] 	INT		NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [MODE]	NVARCHAR (50)	NOT NULL
);
INSERT INTO [dimensional].[MODE] ([MODE]) VALUES ('EEG')
INSERT INTO [dimensional].[MODE] ([MODE]) VALUES ('POW')

CREATE TABLE [dimensional].[ELECTRODE] (
    [ELECTRODE_ID] 	INT		NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [ELECTRODE]		NVARCHAR (50)	NOT NULL,
    [LOCATION]		NVARCHAR (50)	NOT NULL,
    [MODE_ID] 		INT		NOT NULL,
);
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('AF3', 'Front Left', 1)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('AF4', 'Front Right', 1)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('T7', 'Ear Left', 1)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('T8', 'Ear Right', 1)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('Pz', 'Center Back', 1)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('AF3', 'Front Left', 2)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('AF4', 'Front Right, 2')
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('T7', 'Ear Left', 2)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('T8', 'Ear Right', 2)
INSERT INTO [dimensional].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('Pz', 'Center Back', 2)


CREATE TABLE [dimensional].[FREQUENCY] (
    [FREQUENCY_ID] 	INT		NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [FREQUENCY]		NVARCHAR (50)	NOT NULL,
    [ACTIVITY]		NVARCHAR (100)	NOT NULL,
    [ELECTRODE_ID] 	INT		NOT NULL
);
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('THETA', 'Creativity', 1)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('ALPHA', 'Relaxation', 1)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_L', 'Problem Solving', 1)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_H', 'Concentration', 1)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('GAMMA', 'Learning', 1)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('THETA', 'Creativity', 2)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('ALPHA', 'Relaxation', 2)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_L', 'Problem Solving', 2)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_H', 'Concentration', 2)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('GAMMA', 'Learning', 2)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('THETA', 'Creativity', 3)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('ALPHA', 'Relaxation', 3)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_L', 'Problem Solving', 3)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_H', 'Concentration', 3)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('GAMMA', 'Learning', 3)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('THETA', 'Creativity', 4)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('ALPHA', 'Relaxation', 4)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_L', 'Problem Solving', 4)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_H', 'Concentration', 4)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('GAMMA', 'Learning', 4)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('THETA', 'Creativity', 5)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('ALPHA', 'Relaxation', 5)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_L', 'Problem Solving', 5)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_H', 'Concentration', 5)
INSERT INTO [dimensional].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('GAMMA', 'Learning', 5)
