--TOP DOWN
SELECT * FROM [dimensional].[MODE] WHERE [MODE_ID] = 1
SELECT * FROM [dimensional].[MODE] WHERE [MODE_ID] = 2
---------------------
--ELECTRODEs, MODE 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [MODE_ID] = 1
--ELECTRODEs, MODE 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [MODE_ID] = 2
--------------------
--FREQUENCYs, ELECTRODE 1
SELECT * FROM [dimensional].[FREQUENCY] WHERE [ELECTRODE_ID] = 1
--FREQUENCYs, ELECTRODE 2
SELECT * FROM [dimensional].[FREQUENCY] WHERE [ELECTRODE_ID] = 2
--FREQUENCYs, ELECTRODE 3
SELECT * FROM [dimensional].[FREQUENCY] WHERE [ELECTRODE_ID] = 3
--FREQUENCYs, ELECTRODE 4
SELECT * FROM [dimensional].[FREQUENCY] WHERE [ELECTRODE_ID] = 4
--FREQUENCYs, ELECTRODE 5
SELECT * FROM [dimensional].[FREQUENCY] WHERE [ELECTRODE_ID] = 5
