--TOP DOWN
SELECT * FROM [dimensional].[MODE] WHERE [MODE_ID] = 1
SELECT * FROM [dimensional].[MODE] WHERE [MODE_ID] = 1
---------------------
--ELECTRODE 1, MODE 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 1
--ELECTRODE 2, MODE 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 1
--ELECTRODE 3, MODE 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 1
--ELECTRODE 4, MODE 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 1
--ELECTRODE 5, MODE 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 1
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 1
---------------------
--ELECTRODE 1, MODE 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 1 AND [MODE_ID] = 2
--ELECTRODE 2, MODE 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 2 AND [MODE_ID] = 2
--ELECTRODE 3, MODE 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 3 AND [MODE_ID] = 2
--ELECTRODE 4, MODE 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 4 AND [MODE_ID] = 2
--ELECTRODE 5, MODE 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 2
SELECT * FROM [dimensional].[ELECTRODE] WHERE [ELECTRODE_ID] = 5 AND [MODE_ID] = 2
--------------------
--FREQUENCY 1, ELECTRODE 1
SELECT * FROM [dimensional].[FREQUENCY] WHERE [FREQUENCY_ID] = 1 AND [ELECTRODE_ID] = 1
