--CREATE SCHEMA brainwaves
--AUTHORIZATION dbo

CREATE TABLE [brainwaves].[DimMODE] (
  [MODE_ID] 	  INT			NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
  [MODE]		  NVARCHAR (50)	NOT NULL,
  [SYSSTARTTIME]    DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
  [SYSENDTIME]      DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
  PERIOD FOR SYSTEM_TIME (SYSSTARTTIME, SYSENDTIME)
)
WITH (SYSTEM_VERSIONING = ON)
GO
CREATE TABLE [brainwaves].[DimSCENARIO] (
  [SCENARIO_ID]  INT            NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
  [SCENARIO]     NVARCHAR (100) NOT NULL,
  [SYSSTARTTIME]    DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
  [SYSENDTIME]      DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
  PERIOD FOR SYSTEM_TIME (SYSSTARTTIME, SYSENDTIME)
)
WITH (SYSTEM_VERSIONING = ON)
GO
CREATE TABLE [brainwaves].[DimELECTRODE] (
  [ELECTRODE_ID] 	INT			NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
  [ELECTRODE]	NVARCHAR (50)	NOT NULL,
  [LOCATION]	NVARCHAR (50)	NOT NULL,
  [SYSSTARTTIME]    DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
  [SYSENDTIME]      DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
  PERIOD FOR SYSTEM_TIME (SYSSTARTTIME, SYSENDTIME)
)
WITH (SYSTEM_VERSIONING = ON)
GO
CREATE TABLE [brainwaves].[DimFREQUENCY]
(
  [FREQUENCY_ID] 	INT			NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
  [FREQUENCY]	NVARCHAR (50) 	NOT NULL,
  [ACTIVITY]	NVARCHAR (100)	NOT NULL,
  [SYSSTARTTIME]    DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
  [SYSENDTIME]      DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
  PERIOD FOR SYSTEM_TIME (SYSSTARTTIME, SYSENDTIME)
)
WITH (SYSTEM_VERSIONING = ON)
GO
CREATE TABLE [brainwaves].[DimSESSION] (
  [SESSION_ID] 	INT           NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
  [SCENARIO_ID] 	INT           NOT NULL,
  [MODE_ID] 	INT           NOT NULL,
  [SESSION_DATETIME]	DATETIME      NOT NULL,
  [SYSSTARTTIME]    DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
  [SYSENDTIME]      DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
  PERIOD FOR SYSTEM_TIME (SYSSTARTTIME, SYSENDTIME)
)
WITH (SYSTEM_VERSIONING = ON)
GO
--How to delete a temporal table
--ALTER TABLE [brainwaves].[DimMODE] SET ( SYSTEM_VERSIONING = OFF)
--GO
--DROP TABLE [brainwaves].[DimMODE]
--GO
--DROP TABLE [brainwaves].[MSSQL_TemporalHistoryFor_##########]
--GO
