CREATE TABLE [brainwaves].[DimELECTRODE] (
  [ELECTRODE_ID] 	INT			      NOT NULL IDENTITY(1,1),
  [SK_ID]	 	      NVARCHAR (50)	NOT NULL,
  [ELECTRODE]	    NVARCHAR (50)	NOT NULL,
  [LOCATION]	    NVARCHAR (50)	NOT NULL,
  [START_DATE]    DATETIME2 		NOT NULL,
  [END_DATE]      DATETIME2,
  [IS_CURRENT]	  INT
)
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
