DECLARE @SK_ID AS VARCHAR(10)
DECLARE @START_DATE AS DATETIME2 = GETDATE()
IF EXISTS (SELECT * FROM [brainwaves].[DimELECTRODE] WHERE ELECTRODE = 'AF3')
BEGIN
	SELECT @SK_ID = [SK_ID] FROM brainwaves.DimELECTRODE WHERE ELECTRODE = 'AF3'	
	INSERT INTO [brainwaves].[DimELECTRODE] ([SK_ID], [ELECTRODE], [LOCATION], [START_DATE], [END_DATE], [IS_CURRENT]) 
		VALUES (@SK_ID, 'AF3i', 'Top Left', @START_DATE, '9999-12-31 23:59:59', 1)	
	UPDATE [brainwaves].[DimELECTRODE] SET END_DATE = @START_DATE, IS_CURRENT = 0 WHERE ELECTRODE = 'AF3'
END
ELSE
BEGIN
	SELECT @SK_ID = CONCAT('E', COUNT(*) + 1) FROM brainwaves.DimELECTRODE
	INSERT INTO [brainwaves].[DimELECTRODE] ([SK_ID], [ELECTRODE], [LOCATION], [START_DATE], [END_DATE], [IS_CURRENT]) 
		VALUES (@SK_ID, 'AF3i', 'Top Left', @START_DATE, '9999-12-31 23:59:59', 1)
END
