CREATE TABLE [dbo].[SUBJECTS] (
    [ID] 	        INT	    	NOT NULL IDENTITY(1,1),
    [FIRSTNAME]		NVARCHAR (50)	NOT NULL,
    [LASTNAME]		NVARCHAR (50)	NOT NULL,
    [BIRTHDATE]		DATETIME  	NOT NULL,
    [USERNAME] 		NVARCHAR (50)	NOT NULL,
    [ZIPCODE] 		INT	    	NOT NULL,
    [COUNTRY]  		NVARCHAR (50)	NOT NULL,
    [CREATE_DATE]       DATETIME  	NOT NULL
)
WITH
(
    DISTRIBUTION = HASH (ZIPCODE),
    CLUSTERED COLUMNSTORE INDEX
)
GO
INSERT INTO [dbo].[SUBJECTS] ([FIRSTNAME], [LASTNAME], [BIRTHDATE], [USERNAME], [ZIPCODE], [COUNTRY]) VALUES ('BENJAMIN', 'PERKINS', '19880730 08:00:00 AM', 'CSHARPGUITAR', 70000, 'USA', getdate())
INSERT INTO [dbo].[SUBJECTS] ([FIRSTNAME], [LASTNAME], [BIRTHDATE], [USERNAME], [ZIPCODE], [COUNTRY]) VALUES ('RUAL', 'PERKINS', '19180730 08:00:00 AM', 'DANCEMEISTER', 70001, 'USA', getdate())
GO 
SELECT * FROM [dbo].[SUBJECTS]
GO
