ALTER FUNCTION ValuesByFrequency (@frequencyid int)
RETURNS TABLE
AS
RETURN
(
  SELECT TOP 10 sc.SCENARIO, e.ELECTRODE, f.FREQUENCY, 
                CAST(ROUND([VALUE],2,4) AS DECIMAL(19,2)) AS [VALUE]
  FROM SCENARIO sc, [SESSION] s, ELECTRODE e, FREQUENCY f, READING r
  WHERE sc.SCENARIO_ID = s.SCENARIO_ID 
    AND s.SESSION_ID = r.SESSION_ID 
    AND e.ELECTRODE_ID = r.ELECTRODE_ID
    AND f.FREQUENCY_ID = r.FREQUENCY_ID
    AND f.FREQUENCY_ID = @frequencyid
)

SELECT * FROM ValuesByFrequency (1)
