SELECT SCENARIO, COUNT(*) AS [COUNT] FROM [brainwaves].[FactREADING]
GROUP BY SCENARIO
ORDER BY [COUNT]

SELECT COUNT(*) AS [COUNT] FROM [brainwaves].[FactREADING]
SELECT COUNT(*) AS [COUNT] FROM [brainwaves].[TmpREADING]
