SELECT SCENARIO, COUNT(*) AS [COUNT] FROM [brainwaves].[FactREADING]
GROUP BY SCENARIO
ORDER BY [COUNT]

SELECT COUNT(*) AS [COUNT] FROM [brainwaves].[FactREADING]
SELECT COUNT(*) AS [COUNT] FROM [brainwaves].[TmpREADING]

--How many SESSIONs per SCENARIO
SELECT s.SCENARIO, COUNT(*) AS [COUNT] FROM [dbo].[SESSION] se, [dbo].[SCENARIO] s
WHERE se.SCENARIO_ID = s.SCENARIO_ID
GROUP BY SCENARIO
ORDER BY [COUNT] DESC

--Link between SESSION and SCENARIO on READING table
SELECT s.SCENARIO, r.SESSION_ID, COUNT(*) AS [COUNT] 
FROM [dbo].[SESSION] se, [dbo].[SCENARIO] s, dbo.READING r
WHERE r.SESSION_ID = se.SESSION_ID AND se.SCENARIO_ID = s.SCENARIO_ID
GROUP BY s.SCENARIO, r.SESSION_ID
ORDER BY s.SCENARIO ASC
