SELECT DATABASEPROPERTYEX(DB_NAME(), 'Collation') AS Collation; --SQL_Latin1_General_CP1_CI_AS

CREATE TABLE [dbo].[ENCODE] (
    [ENCODE_ID] 	INT		NOT NULL,
    [ENCODE]		VARCHAR (1)	NOT NULL
)
GO
INSERT INTO [dbo].[ENCODE] ([ENCODE_ID], [ENCODE]) VALUES (1, '殽')
INSERT INTO [dbo].[ENCODE] ([ENCODE_ID], [ENCODE]) VALUES (2, 'Ž')
INSERT INTO [dbo].[ENCODE] ([ENCODE_ID], [ENCODE]) VALUES (3, 'ß')
INSERT INTO [dbo].[ENCODE] ([ENCODE_ID], [ENCODE]) VALUES (4, '€')
INSERT INTO [dbo].[ENCODE] ([ENCODE_ID], [ENCODE]) VALUES (5, '陽')

SELECT * FROM [dbo].[ENCODE] ORDER BY [ENCODE_ID]

CREATE TABLE [dbo].[ENCODEN] (
    [ENCODE_ID] 	INT		NOT NULL,
    [ENCODE]		NVARCHAR (1)	NOT NULL
)
INSERT INTO [dbo].[ENCODEN] ([ENCODE_ID], [ENCODE]) VALUES (1, N'殽')
INSERT INTO [dbo].[ENCODEN] ([ENCODE_ID], [ENCODE]) VALUES (2, 'Ž')
INSERT INTO [dbo].[ENCODEN] ([ENCODE_ID], [ENCODE]) VALUES (3, 'ß')
INSERT INTO [dbo].[ENCODEN] ([ENCODE_ID], [ENCODE]) VALUES (4, '€')
INSERT INTO [dbo].[ENCODEN] ([ENCODE_ID], [ENCODE]) VALUES (5, N'陽')

SELECT * FROM [dbo].[ENCODEN] ORDER BY [ENCODE_ID]
