/*CREATE DATABASE brainjammer;*/

/* ------------ target the brainjammer database ------- */
/* ------------ otherwise tables will be in master db ------- */

CREATE TABLE [dbo].[MODE] (
    [MODE_ID] 	INT		NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [MODE]	NVARCHAR (50)	NOT NULL
);
INSERT INTO [dbo].[MODE] ([MODE]) VALUES ('EEG')
INSERT INTO [dbo].[MODE] ([MODE]) VALUES ('POW')

CREATE TABLE [dbo].[SCENARIO] (
    [SCENARIO_ID]  INT            NOT NULL PRIMARY KEY,
    [SCENARIO]     NVARCHAR (MAX) NOT NULL
);

INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (1, N'ClassicalMusic')
INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (2, N'FlipChart')
INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (3, N'Meditation')
INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (4, N'MetalMusic')
INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (5, N'PlayingGuitar')
INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (6, N'TikTok')
INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (7, N'WorkMeeting')
INSERT INTO [dbo].[SCENARIO] ([SCENARIO_ID], [SCENARIO]) VALUES (8, N'WorkNoEmail')

CREATE TABLE [dbo].[ELECTRODE] (
    [ELECTRODE_ID] 	INT		NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [ELECTRODE]		NVARCHAR (50)	NOT NULL,
    [LOCATION]		NVARCHAR (50)	NOT NULL
);
INSERT INTO [dbo].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('AF3', 'Front Left')
INSERT INTO [dbo].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('AF4', 'Front Right')
INSERT INTO [dbo].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('T7', 'Ear Left')
INSERT INTO [dbo].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('T8', 'Ear Right')
INSERT INTO [dbo].[ELECTRODE] ([ELECTRODE], [LOCATION]) VALUES ('Pz', 'Center Back')

CREATE TABLE [dbo].[FREQUENCY] (
    [FREQUENCY_ID] 	INT		NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [FREQUENCY]		NVARCHAR (50)	NOT NULL,
    [ACTIVITY]		NVARCHAR (100)	NOT NULL
);
INSERT INTO [dbo].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('THETA', 'Creativity')
INSERT INTO [dbo].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('ALPHA', 'Relaxation')
INSERT INTO [dbo].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_L', 'Problem Solving')
INSERT INTO [dbo].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('BETA_H', 'Concentration')
INSERT INTO [dbo].[FREQUENCY] ([FREQUENCY], [ACTIVITY]) VALUES ('GAMMA', 'Learning')

CREATE TABLE [dbo].[SESSION] (
    [SESSION_ID] 	INT           NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [SCENARIO_ID] 	INT           NOT NULL,
    [MODE_ID] 		INT           NOT NULL,
    [SESSION_DATETIME]	DATETIME      NOT NULL,
    CONSTRAINT [FK_SESSION_SCENARIO] FOREIGN KEY ([SCENARIO_ID]) REFERENCES [dbo].[SCENARIO] ([SCENARIO_ID]),
    CONSTRAINT [FK_SESSION_MODE] FOREIGN KEY ([MODE_ID]) REFERENCES [dbo].[MODE] ([MODE_ID])
);

INSERT INTO [dbo].[SESSION] ([SCENARIO_ID], [MODE_ID], [SESSION_DATETIME]) VALUES (6,2, '20210730 08:00:00.000 AM')
INSERT INTO [dbo].[SESSION] ([SCENARIO_ID], [MODE_ID], [SESSION_DATETIME]) VALUES (1,1, '20210831 09:30:00.000 AM')
INSERT INTO [dbo].[SESSION] ([SCENARIO_ID], [MODE_ID], [SESSION_DATETIME]) VALUES (5,2, '20210930 09:35:00.000 AM')

CREATE TABLE [dbo].[READING] (
    [READING_ID] 	INT	    NOT NULL IDENTITY(1,1),
    [SESSION_ID] 	INT	    NOT NULL,
    [ELECTRODE_ID] 	INT	    NOT NULL,
    [FREQUENCY_ID] 	INT	    NOT NULL,
    [READING_DATETIME]  DATETIME    NOT NULL,
    [COUNT]      	INT         NOT NULL,
    [VALUE]		DECIMAL(7,3)  NOT NULL,
	CONSTRAINT [PK_READING] PRIMARY KEY CLUSTERED ([READING_ID] ASC, [SESSION_ID] ASC,[ELECTRODE_ID] ASC, [FREQUENCY_ID] ASC),
	CONSTRAINT [FK_READING_SESSION] FOREIGN KEY ([SESSION_ID]) REFERENCES [dbo].[SESSION] ([SESSION_ID]),
	CONSTRAINT [FK_READING_ELECTRODE] FOREIGN KEY ([ELECTRODE_ID]) REFERENCES [dbo].[ELECTRODE] ([ELECTRODE_ID]),
	CONSTRAINT [FK_READING_FREQUENCY] FOREIGN KEY ([FREQUENCY_ID]) REFERENCES [dbo].[FREQUENCY] ([FREQUENCY_ID])
);
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (1, 1, 1, '20210730 08:02:49.685 AM', 0, 9.681)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (1, 1, 2, '20210730 08:02:49.685 AM', 0, 3.849)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (1, 1, 3, '20210730 08:02:49.685 AM', 0, 2.582)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (1, 1, 4, '20210730 08:02:49.685 AM', 0, 0.959)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (1, 1, 5, '20210730 08:02:49.685 AM', 0, 0.738)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (2, 1, 1, '20210831 09:34:53.685 AM', 0, 4144.103)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (2, 2, 2, '20210831 09:34:53.685 AM', 0, 4135.385)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (2, 3, 3, '20210831 09:34:53.685 AM', 0, 3582.051)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (2, 4, 4, '20210831 09:34:53.685 AM', 0, 4137.436)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (2, 5, 5, '20210831 09:34:53.685 AM', 0, 4058.462)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (3, 2, 1, '20210930 09:37:18.558 AM', 1, 26.25)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (3, 2, 2, '20210930 09:37:18.558 AM', 1, 5.549)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (3, 2, 3, '20210930 09:37:18.558 AM', 1, 2.058)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (3, 2, 4, '20210930 09:37:18.558 AM', 1, 0.895)
INSERT INTO [dbo].[READING] ([SESSION_ID], [ELECTRODE_ID], [FREQUENCY_ID], [READING_DATETIME], [COUNT], [VALUE]) VALUES (3, 2, 5, '20210930 09:37:18.558 AM', 1, 0.839)
