SELECT m.MODE, sc.SCENARIO, e.ELECTRODE, f.FREQUENCY, AVG([VALUE]) AS AVG,
       SUM([VALUE]) AS SUM, STDEV([VALUE]) AS STDEV, STDEVP([VALUE]) AS STDEVP,
       VAR([VALUE]) AS VAR, VARP([VALUE]) AS VARP, 
       TAN(AVG([VALUE])) AS TANAVG, TAN(SUM([VALUE])) AS TANSUM, 
       LOG(AVG([VALUE])) AS LOGAVG, LOG(SUM([VALUE])) AS LOGSUM,
       COS(AVG([VALUE])) AS COSAVG, COS(SUM([VALUE])) AS COSSUM,
       SIN(AVG([VALUE])) AS SINAVG, SIN(SUM([VALUE])) AS SINSUM,
       COT(AVG([VALUE])) AS COTAVG, COT(SUM([VALUE])) AS COTSUM
INTO READINGSTATS
FROM MODE m, SCENARIO sc, [SESSION] s, ELECTRODE e, FREQUENCY f, READING r
WHERE m.MODE_ID = s.MODE_ID 
    AND sc.SCENARIO_ID = s.SCENARIO_ID 
    AND s.SESSION_ID = r.SESSION_ID 
    AND e.ELECTRODE_ID = r.ELECTRODE_ID
    AND f.FREQUENCY_ID = r.FREQUENCY_ID
GROUP BY m.MODE, sc.SCENARIO, e.ELECTRODE, f.FREQUENCY

/* For example only, the INTO READINGSTATS creates the table

CREATE TABLE [dbo].[READINGSTATS] (
	[MODE] 		NVARCHAR (50) 	NOT NULL,
    	[SCENARIO]	NVARCHAR (MAX) 	NOT NULL,
    	[ELECTRODE] 	NVARCHAR (50) 	NOT NULL,
	[FREQUENCY] 	NVARCHAR (50)   NOT NULL,
	[AVG]		DECIMAL(10,6) 	NOT NULL,
	[SUM] 		DECIMAL(10,6) 	NOT NULL,
	[STDEV]		FLOAT	  	NOT NULL,
	[STDEVP] 	FLOAT	 	NOT NULL,
	[VAR] 		FLOAT	  	NOT NULL,
	[VARP] 		FLOAT	  	NOT NULL,
	[TANAVG]	FLOAT	 	NOT NULL,
	[TANSUM]	FLOAT	 	NOT NULL,
	[LOGAVG]	FLOAT	 	NOT NULL,
	[LOGSUM]	FLOAT	 	NOT NULL,
	[COSAVG]	FLOAT	 	NOT NULL,
	[COSSUM]	FLOAT	 	NOT NULL,
	[SINAVG]	FLOAT	 	NOT NULL,
	[SINSUM]	FLOAT	 	NOT NULL,
	[COTAVG]	FLOAT	 	NOT NULL,
	[COTSUM]	FLOAT	 	NOT NULL
);*/
