--build tables into brainwves schema
--DROP TABLE [brainwaves].[SCENARIO]
--GO
--DROP TABLE [brainwaves].[ELECTRODE]
--GO
--DROP TABLE [brainwaves].[FREQUENCY]
--GO
--DROP TABLE [brainwaves].[SCENARIO_ELECTRODE]
--GO
--DROP TABLE [brainwaves].[SCENARIO_FREQUENCY] 
--GO
--DROP TABLE [brainwaves].[SCENARIO_ELECTRODE_FREQUENCY]
--GO
CREATE TABLE [brainwaves].[SCENARIO]
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
AS
SELECT DISTINCT SCENARIO,
       AVG([VALUE]) OVER (partition by SCENARIO) as AVERAGE,
       STDEV([VALUE]) OVER (partition by SCENARIO) as STANDARDDEV,
       VAR([VALUE]) OVER (partition by SCENARIO) as VARIANCE,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO) as MEDIAN,
       SQRT(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO)) AS SQUAREROOT,
       SQUARE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO)) AS SQUARED
FROM brainwaves.FactREADING
GO
SELECT * FROM [brainwaves].[SCENARIO] ORDER BY SCENARIO
GO
CREATE TABLE [brainwaves].[ELECTRODE]
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
AS
SELECT DISTINCT ELECTRODE,
       AVG([VALUE]) OVER (partition by ELECTRODE) as AVERAGE, 
       STDEV([VALUE]) OVER (partition by ELECTRODE) as STANDARDDEV,
       VAR([VALUE]) OVER (partition by ELECTRODE) as VARIANCE,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by ELECTRODE) as MEDIAN,
       SQRT(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by ELECTRODE)) AS SQUAREROOT,
       SQUARE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by ELECTRODE)) AS SQUARED
FROM brainwaves.FactREADING
GO
SELECT * FROM [brainwaves].[ELECTRODE] ORDER BY ELECTRODE
GO
CREATE TABLE [brainwaves].[FREQUENCY]
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
AS
SELECT DISTINCT FREQUENCY,
       AVG([VALUE]) OVER (partition by FREQUENCY) as AVERAGE,
       STDEV([VALUE]) OVER (partition by FREQUENCY) as STANDARDDEV,
       VAR([VALUE]) OVER (partition by FREQUENCY) as VARIANCE,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by FREQUENCY) as MEDIAN,
       SQRT(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by FREQUENCY)) AS SQUAREROOT,
       SQUARE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by FREQUENCY)) AS SQUARED
FROM brainwaves.FactREADING
GO
SELECT * FROM [brainwaves].[FREQUENCY] ORDER BY FREQUENCY
GO
CREATE TABLE [brainwaves].[SCENARIO_ELECTRODE]
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
AS
SELECT DISTINCT SCENARIO, ELECTRODE,
       AVG([VALUE]) OVER (partition by SCENARIO, ELECTRODE) as AVERAGE, 
       STDEV([VALUE]) OVER (partition by SCENARIO, ELECTRODE) as STANDARDDEV,
       VAR([VALUE]) OVER (partition by SCENARIO, ELECTRODE) as VARIANCE,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, ELECTRODE) as MEDIAN,
       SQRT(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, ELECTRODE)) AS SQUAREROOT,
       SQUARE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, ELECTRODE)) AS SQUARED
FROM brainwaves.FactREADING
GO
SELECT * FROM [brainwaves].[SCENARIO_ELECTRODE] ORDER BY SCENARIO, ELECTRODE
GO
CREATE TABLE [brainwaves].[SCENARIO_FREQUENCY]
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
AS
SELECT DISTINCT SCENARIO, FREQUENCY,
       AVG([VALUE]) OVER (partition by SCENARIO, FREQUENCY) as AVERAGE,
       STDEV([VALUE]) OVER (partition by SCENARIO, FREQUENCY) as STANDARDDEV,
       VAR([VALUE]) OVER (partition by SCENARIO, FREQUENCY) as VARIANCE,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, FREQUENCY) as MEDIAN,
       SQRT(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, FREQUENCY)) AS SQUAREROOT,
       SQUARE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, FREQUENCY)) AS SQUARED
FROM brainwaves.FactREADING
GO
SELECT * FROM [brainwaves].[SCENARIO_FREQUENCY] WHERE SCENARIO = 'TikTok' ORDER BY SCENARIO, FREQUENCY
GO
CREATE TABLE [brainwaves].[SCENARIO_ELECTRODE_FREQUENCY]
WITH
(
  CLUSTERED COLUMNSTORE INDEX,
  DISTRIBUTION = REPLICATE
)
AS
SELECT DISTINCT SCENARIO, ELECTRODE, FREQUENCY,
       AVG([VALUE]) OVER (partition by SCENARIO, ELECTRODE, FREQUENCY) as AVERAGE,
       STDEV([VALUE]) OVER (partition by SCENARIO, ELECTRODE, FREQUENCY) as STANDARDDEV,
       VAR([VALUE]) OVER (partition by SCENARIO, ELECTRODE, FREQUENCY) as VARIANCE,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, ELECTRODE, FREQUENCY) as MEDIAN,
       SQRT(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, ELECTRODE, FREQUENCY)) AS SQUAREROOT,
       SQUARE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY [VALUE]) OVER (partition by SCENARIO, ELECTRODE, FREQUENCY)) AS SQUARED
FROM brainwaves.FactREADING
GO
SELECT * FROM [brainwaves].[SCENARIO_ELECTRODE_FREQUENCY] ORDER BY SCENARIO, ELECTRODE, FREQUENCY
