SELECT COUNT(*) FROM brainwaves.FactREADING
--4539223
SELECT COUNT(*)
FROM brainwaves.FactREADING
WHERE [VALUE] < 0.274 OR [VALUE] > 392
--99278
SELECT * INTO brainwaves.FactREADINGHighLow
FROM brainwaves.FactREADING
WHERE [VALUE] < 0.274 OR [VALUE] > 392  
SELECT COUNT(*) FROM brainwaves.FactREADINGHighLow
--99278
DELETE FROM brainwaves.FactREADING WHERE [VALUE] < 0.274
DELETE FROM brainwaves.FactREADING WHERE [VALUE] > 392
SELECT COUNT(*) FROM brainwaves.FactREADING
--4438073
